### ISSUE TITLE
Example functions not working

### ISSUE THREAD

**Issue by Henshall** [schulzefelix/laravel-adwords-targeting-idea-service#11]
When using:
$searchVolumes = AdWords::searchVolumes(['cheesecake', 'coffee']);

I get the error: 
Non-static method SchulzeFelix\AdWords\AdWords::searchVolumes() should not be called statically

I tried to use the methods as stated in the readme, but it seems they cannot be called statically. Creating an instance of the object also cannot work since its constructor takes AdWordsService class as an argument.

**Comment by schulzefelix** [comment]
I guess you have this use statement:

use SchulzeFelix\AdWords\AdWords;

If so, change it to:
use AdWords;

**Comment by Henshall** [comment]
Great thanks for the help! that did fix the problem, but now it seems to just hang... I think i just didnt set up the credentials properly or something. I will work on this Thank you!

**Comment by schulzefelix** [comment]
How many keywords did you throw in there? Google just allow to request batches of 700 keywords, if you request more the package will split them up and does multiple requests and this can take some time, specially when the Adwords API returned an error it gonna retry the request.

**Comment by Henshall** [comment]
I just have 2 keywords like the example:

use AdWords;
public function welcome()
    { 
        $searchVolumes = AdWords::searchVolumes(['cheesecake', 'coffee']);
        dd($searchVolumes); 
    }

but it hangs. Maybe its because I only have a test developer token? Or maybe because with: php artisan adwords:token  it gives me the error: 

"error": "invalid_grant",
  "error_description": "Malformed auth code."

I can try to get this working over the next few days... the access token I got from google should of worked...

**Comment by schulzefelix** [comment]
Ok, yeah then you have to figure out where the error is. But "Malformed auth code" shouldn't come there, because you need a proper refresh token.
