### ISSUE TITLE
Non-static method -  AdWords

### ISSUE THREAD

**Issue by Bilalvaival123** [schulzefelix/laravel-adwords-targeting-idea-service#13]
After Following all the procedure, i have make call to the following methods as defined in the documentation.

$keywordIdeas = AdWords::keywordIdeas('coffee');
$searchVolumes = AdWords::searchVolumes(['cheesecake', 'coffee']);

I am getting the following error
* **Non-static method SchulzeFelix\AdWords\AdWords::searchVolumes() should not be called statically** *

**Comment by schulzefelix** [comment]
You should check out the old issue for that #11
