### ISSUE TITLE
Loading issue

### ISSUE THREAD

**Issue by Bilalvaival123** [schulzefelix/laravel-adwords-targeting-idea-service#14]
Site keeps on loading, i have provided all the details but its still not wokring

Ticket #8 issue is also not resolved.

**Comment by schulzefelix** [comment]
You could debug the Exception in ExponentialBackoff.php, to what new error (code) Google maybe throw by now

**Comment by schulzefelix** [comment]
Figured it out?

**Comment by Bilalvaival123** [comment]
Not yet, It still not working. Have you work on Finding the main Keyword (seed Keyword) by title of the product?

Thanks
Sent from Mail for Windows 10

**Comment by schulzefelix** [comment]
Like I said before you need to figure out what exception google giving you to figure out whats the problem. That package works fine for me and in production env.

And no there no plans to add new features to that package. Feels free to add new one via a proper PR.

**Comment by schulzefelix** [comment]
closed due inactivity

**Comment by nixuiui** [comment]
Hi, i just fix my problem that same with you...
maybe the CUSTOMER_ID that you choose is for production account.
Just change the CUSTOMER_ID for Test Account.

Makesure if the account is "Test Account"
<img width="375" alt="Screen Shot 2021-03-22 at 13 58 56" src="https://user-images.githubusercontent.com/11423121/111951931-e906a400-8b16-11eb-83f8-d6487242b17d.png">

How to create Test Account, you can see this site:
https://developers.google.com/adwords/api/docs/guides/accounts-overview#test_accounts

**Comment by nixuiui** [comment]
Hi, i just fix my problem that same with you...
maybe the CUSTOMER_ID that you choose is for production account.
Just change the CUSTOMER_ID for Test Account.

Makesure if the account is "Test Account"
<img width="274" alt="Screen Shot 2021-03-22 at 14 01 18" src="https://user-images.githubusercontent.com/11423121/111952089-29662200-8b17-11eb-839f-0184e4fe34c4.png">

How to create Test Account, you can see this site:
https://developers.google.com/adwords/api/docs/guides/accounts-overview#test_accounts
