### ISSUE TITLE
Carrying out steps

### ISSUE THREAD

**Issue by matteoFeduzi** [schulzefelix/laravel-adwords-targeting-idea-service#15]
Can you better explain the steps to follow once your code is installed using the composer command?

Thanks so much.

**Comment by schulzefelix** [comment]
Where exactly is the problem? YOu need to enter your credentials, generate the refresh token and you good to go to use.

**Comment by matteoFeduzi** [comment]
Do you still need to use the base access livel to use your code effectively?

Or do you also need a trial account?

Thanks so much.

**Comment by schulzefelix** [comment]
What exactly you mean with trial account? I was usign it with with the Basic Access.
It's just wrapper aroud Googles API, so the same rules like Google mentioned here are apply: https://developers.google.com/adwords/api/docs/access-levels

**Comment by matteoFeduzi** [comment]
Can I ask you how did you get the "basic access"?

I currently have the "Test account access".

I'm trying to get "basic access" in every way but they don't release me...

As soon as I tell them I want to get this type of data they say I have to use their Keyword Planner.

Thanks so much.

**Comment by schulzefelix** [comment]
Sorry, can't help you with that.
