### ISSUE TITLE
Issue in php artisan adwords:token

### ISSUE THREAD

**Issue by YuvrajHinger** [schulzefelix/laravel-adwords-targeting-idea-service#20]
php artisan adwords:token
```
Please sign in to your AdWords account, and open following url:


   InvalidArgumentException

  missing the required client identifier

  at C:\Users\yuvrajhinger.in\Desktop\yuvrajhinger.in\blogapk\vendor\google\auth\src\OAuth2.php:670
    666|         ], $config);
    667|
    668|         // Validate the auth_params
    669|         if (is_null($params['client_id'])) {
  > 670|             throw new InvalidArgumentException(
    671|                 'missing the required client identifier'
    672|             );
    673|         }
    674|         if (is_null($params['redirect_uri'])) {

  1   C:\Users\yuvrajhinger.in\Desktop\yuvrajhinger.in\blogapk\vendor\schulzefelix\laravel-adwords-targeting-idea-service\src\Commands\GenerateRefreshTokenCommand.php:65
      Google\Auth\OAuth2::buildFullAuthorizationUri(["offline"])

  2   C:\Users\yuvrajhinger.in\Desktop\yuvrajhinger.in\blogapk\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:37
      SchulzeFelix\AdWords\Commands\GenerateRefreshTokenCommand::handle()
```

**_Help me to fix that_**

**Comment by schulzefelix** [comment]
I guess it helps if you fill in the Client ID, seems to be null if I look at the error.

From the installation guide: "This requires that the clientId and clientSecret are from a native application."

**Comment by YuvrajHinger** [comment]
Can You Please Help Me Where To Fill Client Id & Secret.
As I am little bit confused on which file you are taking about.

Looking forward for your response.

Thanks.

**Comment by YuvrajHinger** [comment]
Can You Please Help Me Where To Fill Client Id & Secret.
As I am little bit confused on which file you are talking about.

**Comment by schulzefelix** [comment]
In the config file, you need to set your vars (ADWORDS_CLIENT_ID and ADWORDS_CLIENT_SECRET) in your .env file

`    /*
    |--------------------------------------------------------------------------
    | OAUTH2 Credentials
    |--------------------------------------------------------------------------
    */

    'client_id'            => env('ADWORDS_CLIENT_ID'),
    'client_secret'        => env('ADWORDS_CLIENT_SECRET'),
    'client_refresh_token' => env('ADWORDS_CLIENT_REFRESH_TOKEN'),`
