### ISSUE TITLE
Not Throwing an Exception for the Ads API Error "QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED"

### ISSUE THREAD

**Issue by prageeth-peiris** [schulzefelix/laravel-adwords-targeting-idea-service#21]
Hi,

I was accidentally using a  not approved developer token with a  Google Ads production  account. But the  response was in pending situation and did not give an exception. When I debug the soap response , I found out the reason. Here is the soap error.

`SoapFault {#1984
  #message: "[QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED @ ; trigger:'<null>']"
  #code: 0
  #file: "\API\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php"
  #line: 150
  +"faultstring": "[QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED @ ; trigger:'<null>']"
  +"faultcode": "soap:Server"
  +"detail": {#1987
    +"ApiExceptionFault": {#1988
      +"message": "[QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED @ ; trigger:'<null>']"
      +"ApplicationException.Type": "ApiException"
      +"errors": SoapVar {#1986
        +"enc_type": 0
        +"enc_value": Google\AdsApi\AdWords\v201809\cm\QuotaCheckError {#1969
          #reason: "DEVELOPER_TOKEN_NOT_APPROVED"
          #fieldPath: ""
          #fieldPathElements: null
          #trigger: "<null>"
          #errorString: "QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED"
          #ApiErrorType: "QuotaCheckError"
          -parameterMap: array:1 [
            "ApiError.Type" => "ApiErrorType"
          ]
        }
        +"enc_stype": "QuotaCheckError"
        +"enc_ns": "https://adwords.google.com/api/adwords/cm/v201809"
      }
    }
  }`

Can you  please add the functionality to raise an exception for this scenario?

Anyway appreciate your hard work for this package!!!

**Comment by schulzefelix** [comment]
Thanks, added in the latest version
https://github.com/schulzefelix/laravel-adwords-targeting-idea-service/releases/tag/1.8.0
