### ISSUE TITLE
Support for Laravel < 5.7.11 

### ISSUE THREAD

**Issue by tocka9** [schulzefelix/laravel-adwords-targeting-idea-service#4]
Hi, when installing your package, I received these errors from composer:

Problem 1
    - Conclusion: remove laravel/framework v5.7.11
    - Conclusion: don't install laravel/framework v5.7.11
    - schulzefelix/laravel-adwords-targeting-idea-service 1.3.0 requires illuminate/support ~5.5.0 -> satisfiable by illuminate/support[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - schulzefelix/laravel-adwords-targeting-idea-service 1.3.1 requires illuminate/support ~5.5.0 -> satisfiable by illuminate/support[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - schulzefelix/laravel-adwords-targeting-idea-service 1.3.2 requires illuminate/support ~5.5.0|~5.6.0 -> satisfiable by illuminate/support[5.5.x-dev, 5.6.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - illuminate/support 5.5.x-dev conflicts with laravel/framework[v5.7.11].
    - illuminate/support v5.5.0 conflicts with laravel/framework[v5.7.11].
    - illuminate/support v5.5.16 conflicts with laravel/framework[v5.7.11].
    - illuminate/support v5.5.17 conflicts with laravel/framework[v5.7.11].
    - illuminate/support v5.5.2 conflicts with laravel/framework[v5.7.11].
    - illuminate/support v5.5.28 conflicts with laravel/framework[v5.7.11].
    - illuminate/support v5.5.35 conflicts with laravel/framework[v5.7.11].
    - illuminate/support v5.5.36 conflicts with laravel/framework[v5.7.11].
    - illuminate/support v5.5.37 conflicts with laravel/framework[v5.7.11].
    - illuminate/support v5.5.39 conflicts with laravel/framework[v5.7.11].
    - illuminate/support v5.5.40 conflicts with laravel/framework[v5.7.11].
    - illuminate/support v5.5.41 conflicts with laravel/framework[v5.7.11].
    - illuminate/support v5.5.43 conflicts with laravel/framework[v5.7.11].
    - illuminate/support v5.5.44 conflicts with laravel/framework[v5.7.11].
    - illuminate/support v5.6.4 conflicts with laravel/framework[v5.7.11].
    - illuminate/support v5.6.5 conflicts with laravel/framework[v5.7.11].
    - illuminate/support v5.6.6 conflicts with laravel/framework[v5.7.11].
    - illuminate/support v5.6.7 conflicts with laravel/framework[v5.7.11].
    - don't install illuminate/support 5.6.x-dev|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.5.33|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.5.34|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.0|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.1|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.10|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.11|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.12|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.13|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.14|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.15|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.16|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.17|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.19|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.2|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.20|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.21|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.22|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.23|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.24|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.25|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.26|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.27|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.28|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.29|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.3|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.30|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.31|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.32|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.33|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.34|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.35|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.36|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.37|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.38|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.39|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.8|don't install laravel/framework v5.7.11
    - don't install illuminate/support v5.6.9|don't install laravel/framework v5.7.11
    - Installation request for laravel/framework (locked at v5.7.11, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.11].
    - Installation request for schulzefelix/laravel-adwords-targeting-idea-service ^1.3 -> satisfiable by schulzefelix/laravel-adwords-targeting-idea-service[1.3.0, 1.3.1, 1.3.2].

**Comment by schulzefelix** [comment]
Hi,

I just release a new version, its compatible with Laravel 5.7 now.

https://github.com/schulzefelix/laravel-adwords-targeting-idea-service/releases/tag/1.3.3

**Comment by 2solidtechnologies** [comment]
seems to not work correctly after installation in 5.7. Can you provide some further installation instructions? one cannot call the facade using Adwords::searchVolume.. etc, etc.

**Comment by schulzefelix** [comment]
Hi, are you sure you installing version 1.3.3 ? I just tried it with the current version 5.7.24 and the specific 5.7.11 of Laravel and don't have any problems.

```
☁  test57  composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 8 removals
  - Removing zendframework/zend-diactoros (1.8.6)
  - Removing php-http/promise (v1.0.0)
  - Removing php-http/httplug (v1.1.0)
  - Removing php-http/guzzle6-adapter (v1.1.1)
  - Removing nexmo/client (1.6.1)
  - Removing lcobucci/jwt (3.2.5)
  - Removing laravel/slack-notification-channel (v1.0.3)
  - Removing laravel/nexmo-notification-channel (v1.0.1)
  - Downgrading laravel/framework (v5.7.24 => v5.7.11): Downloading (100%)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: schulzefelix/laravel-adwords-targeting-idea-service
Package manifest generated successfully.
☁  test57```
