### ISSUE TITLE
Error when trying to fetch data from Google Adwords API

### ISSUE THREAD

**Issue by tocka9** [schulzefelix/laravel-adwords-targeting-idea-service#5]
When trying to use any method (as in the examples you provided)

Im getting this error:

`[TargetingIdeaError.INVALID_SEARCH_PARAMETERS @ selector.searchParameters.searchParameters[0]; trigger:'LocationSearchParameter', TargetingIdeaError.INVALID_SEARCH_PARAMETERS @ selector.searchParameters.searchParameters[1]; trigger:'RelatedToQuerySearchParameter', TargetingIdeaError.INVALID_SEARCH_PARAMETERS @ selector.searchParameters.searchParameters[2]; trigger:'NetworkSearchParameter']`

Code used:
```
$get = AdWords::location(2276)->searchVolumes(['cheesecake', 'coffee']);
dd2($get);
```

**Comment by schulzefelix** [comment]
Hi,

did you set a valid value for ADWORDS_CLIENT_CUSTOMER_ID ? I get the same error when I remove it from my .env file.

(I will add a proper exception soon)

**Comment by tocka9** [comment]
Hi,

Yes it worked :) Thanks!
