### ISSUE TITLE
"Can only install one of: nesbot/carbon"

### ISSUE THREAD

**Issue by KirksFletcher** [schulzefelix/laravel-adwords-targeting-idea-service#7]
Trying to install on fresh composer install of Laravel 5.8.0.

Error message: 
Problem 1
    - schulzefelix/laravel-adwords-targeting-idea-service 1.4.0 requires schulzefelix/laravel-data-transfer-object ^1.0.0 -> satisfiable by schulzefelix/laravel-data-transfer-object[1.0.0].
    - Installation request for schulzefelix/laravel-adwords-targeting-idea-service ^1.4 -> satisfiable by schulzefelix/laravel-adwords-targeting-idea-service[1.4.0].
    - Conclusion: remove nesbot/carbon 2.14.2
    - Conclusion: don't install nesbot/carbon 2.14.2
    - schulzefelix/laravel-data-transfer-object 1.0.0 requires nesbot/carbon ^1.21 -> satisfiable by nesbot/carbon[1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2].
    - Can only install one of: nesbot/carbon[1.26.3, 2.14.2].
    - Can only install one of: nesbot/carbon[1.26.4, 2.14.2].
    - Can only install one of: nesbot/carbon[1.27.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.28.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.29.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.29.1, 2.14.2].
    - Can only install one of: nesbot/carbon[1.29.2, 2.14.2].
    - Can only install one of: nesbot/carbon[1.30.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.31.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.31.1, 2.14.2].
    - Can only install one of: nesbot/carbon[1.32.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.33.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.34.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.34.1, 2.14.2].
    - Can only install one of: nesbot/carbon[1.34.2, 2.14.2].
    - Can only install one of: nesbot/carbon[1.34.3, 2.14.2].
    - Can only install one of: nesbot/carbon[1.34.4, 2.14.2].
    - Can only install one of: nesbot/carbon[1.35.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.35.1, 2.14.2].
    - Can only install one of: nesbot/carbon[1.36.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.36.1, 2.14.2].
    - Can only install one of: nesbot/carbon[1.36.2, 2.14.2].
    - Can only install one of: nesbot/carbon[1.21.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.22.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.22.1, 2.14.2].
    - Can only install one of: nesbot/carbon[1.23.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.24.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.24.1, 2.14.2].
    - Can only install one of: nesbot/carbon[1.24.2, 2.14.2].
    - Can only install one of: nesbot/carbon[1.25.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.26.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.26.1, 2.14.2].
    - Can only install one of: nesbot/carbon[1.26.2, 2.14.2].
    - Installation request for nesbot/carbon (locked at 2.14.2) -> satisfiable by nesbot/carbon[2.14.2].

Installation failed, reverting ./composer.json to its original content.

I really like the look of this package and would love to use it. Can you update dependancy issue on the other package please :-)

**Comment by schulzefelix** [comment]
Hey, should be fixed with the new release:

https://github.com/schulzefelix/laravel-adwords-targeting-idea-service/releases/tag/1.4.1
