### ISSUE TITLE
Keeps loading

### ISSUE THREAD

**Issue by roverdev** [schulzefelix/laravel-adwords-targeting-idea-service#8]
I use laravel v5.8.11. 

**Walked through the steps:**

- created a manager account
- connected it to a normal account
- got temp (google ads) dev token
- published the provider
- created a cloud console projects + enabled ads api + got oauth clientid + secret
- generated refresh token, copied the one returned by the terminal to my .env file

Launched a small code:
        $keywordIdeas = \AdWords::keywordIdeas('coffee');
        dd($keywordIdeas);

**Now it says:**
(1/1) ClientException
Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:
{
"error": "invalid_request",
"error_description": "Missing required parameter: refresh_token"
}

**So created a new one:**

- php artisan adwords:token
-Signed in with same account as google cloud (tried my normal ads account & manager account)
-refreshed the refresh-token in the .env file

**Now**
Page keeps loading and loading and finally returns the same error.

Thanks for the assitance!

**Comment by schulzefelix** [comment]
Hi,

I pushed a fix that the code will throw the exception early in case of a response code 400 too.
Anyway, that doesn't solve your problem, just showing you the error.

I can reproduce the error when my token variable is empty in the .env file:
```
ADWORDS_CLIENT_REFRESH_TOKEN=
```

Did you try to refresh the config cache after you copied the token in there?

**Comment by badrshs** [comment]
I got same issue here , On
`"laravel/framework": "5.8.*"`
I did all required steps for client_refresh_token , im not using .env , I past it immediately
 to` (adwords-targeting-idea-service.php)`

thanks again for helping
