### ISSUE TITLE
Is it possible to set location to United States ?

### ISSUE THREAD

**Issue by swash13** [schulzefelix/laravel-adwords-targeting-idea-service#9]
Is it possible to set location to United States ? 
For geotargeting i can pass only CriteriaId, which is some city, but not the whole country ?

**Comment by schulzefelix** [comment]
For sure, just follow the link in the readme

```
For Criteria ID see https://developers.google.com/adwords/api/docs/appendix/geotargeting
```

And there you can find the United States with the ID 2840
